/**
 * Oracle tests for the .blg (bibliography log) parser. The *.blg fixtures were generated by
 * this project: known-broken .bib files run through TeX Live 2025 bibtex / biber (LaTeX passes
 * with -interaction=nonstopmode -no-shell-escape). Expected values were read off the raw logs
 * by hand.
 */
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { parseBibLog, parseCompileDiagnostics } from '../../../../src/lib/latex-log';

const fixture = (name: string) => readFileSync(join(__dirname, 'fixtures', name), 'utf8');

describe('parseBibLog: classic BibTeX', () => {
	it('bibtex-errors: syntax error with line+file, bad crossref, keyed warnings', () => {
		const r = parseBibLog(fixture('bibtex-errors.blg'));
		expect(r.tool).toBe('bibtex');

		const errors = r.entries.filter((e) => e.level === 'error');
		expect(errors.length).toBe(2);
		expect(errors[0].message).toBe("I was expecting a `,' or a `}'");
		expect(errors[0].line).toBe(15);
		expect(errors[0].file).toBe('refs.bib');
		expect(errors[0].context).toContain('@inproceedings{crossref-bad,');
		expect(errors[1].message).toBe('A bad cross reference---entry "crossref-bad" refers to entry "no-such-parent", which doesn\'t exist');

		const warnings = r.entries.filter((e) => e.level === 'warning');
		expect(warnings.map((w) => w.message)).toEqual([
			'I didn\'t find a database entry for "doesnotexist"',
			'I didn\'t find a database entry for "no-such-parent"',
			'empty journal in broken1',
			'empty year in broken1',
			'empty booktitle in crossref-bad',
			'empty year in crossref-bad'
		]);
		// keyed warnings attribute to the single database file in play
		expect(warnings[2].file).toBe('refs.bib');
		// every entry is tagged as bibliography-sourced
		expect(r.entries.every((e) => e.source === 'bib')).toBe(true);
	});

	it('bibtex-nostyle: missing .bst with location from the continuation line', () => {
		const r = parseBibLog(fixture('bibtex-nostyle.blg'));
		expect(r.tool).toBe('bibtex');
		const errors = r.entries.filter((e) => e.level === 'error');
		expect(errors[0].message).toBe("I couldn't open style file no-such-style.bst");
		expect(errors[0].line).toBe(3);
		expect(errors[0].file).toBe('main.aux');
		expect(errors.some((e) => e.message.startsWith('I found no style file'))).toBe(true);
	});

	it('never reads the stats tail as diagnostics', () => {
		const r = parseBibLog(fixture('bibtex-errors.blg'));
		expect(r.entries.some((e) => /wiz_defined|built_in/.test(e.message))).toBe(false);
	});
});

describe('parseBibLog: biber', () => {
	it('biber-errors: temp .utf8 path is mapped back to the real .bib, line preserved', () => {
		const r = parseBibLog(fixture('biber-errors.blg'));
		expect(r.tool).toBe('biber');

		const errors = r.entries.filter((e) => e.level === 'error');
		expect(errors.length).toBe(1);
		expect(errors[0].file).toBe('refs.bib');
		expect(errors[0].line).toBe(14);
		expect(errors[0].message).toContain('syntax error: at end of input');
		expect(errors[0].message).toContain('refs.bib');
		expect(errors[0].message).not.toContain('biber_tmp');

		const warnings = r.entries.filter((e) => e.level === 'warning');
		expect(warnings.length).toBe(1);
		expect(warnings[0].message).toContain('possible runaway string started at line 10');
		expect(warnings[0].line).toBe(11); // the warning's own location comes first in the message
		expect(warnings[0].file).toBe('refs.bib');
	});

	it('INFO records never become entries', () => {
		const r = parseBibLog(fixture('biber-errors.blg'));
		expect(r.entries.length).toBe(2);
	});
});

describe('parseCompileDiagnostics (merged .log + .blg)', () => {
	it('appends enriched bib entries after the engine entries', () => {
		const r = parseCompileDiagnostics(fixture('warnings.log'), fixture('bibtex-errors.blg'));
		const bib = r.entries.filter((e) => e.source === 'bib');
		expect(bib.length).toBe(8);
		// enrichment applies to bib entries too
		const notFound = r.warnings.find((w) => w.ruleId === 'bib-entry-not-found');
		expect(notFound).toBeDefined();
		expect(notFound!.hint).toContain('doesnotexist');
		const syntax = r.errors.find((e) => e.ruleId === 'bib-syntax-error');
		expect(syntax).toBeDefined();
		// engine entries are still there
		expect(r.warnings.some((w) => w.ruleId === 'undefined-reference')).toBe(true);
	});

	it('handles a missing/empty blg gracefully', () => {
		const r = parseCompileDiagnostics(fixture('warnings.log'), null);
		expect(r.entries.filter((e) => e.source === 'bib')).toEqual([]);
		const r2 = parseCompileDiagnostics(fixture('warnings.log'), '');
		expect(r2.entries.filter((e) => e.source === 'bib')).toEqual([]);
	});
});
